
 - pipeline.id: test
   pipeline.workers: 1
   pipeline.batch.size: 1
   config.string: "input { generator {} } filter { sleep { time => 1 } } output { stdout { codec => dots } }"
 
 - pipeline.id: nyse
   queue.type: persisted
   pipeline.workers: 1
   pipeline.batch.size: 1
   path.config: "/tmp/logstash/nyse_data.conf"